{% set version = "1.42" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-factominer
  version: {{ version|replace("-", "_") }}

source:
  fn: FactoMineR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/FactoMineR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FactoMineR/FactoMineR_{{ version }}.tar.gz
  sha256: 4cd9efb3681767c3bd48ddc3504ebead1493fcbbc0a9f759a00955b16c3481fa

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-car
    - r-cluster
    - r-ellipse
    - r-flashclust
    - r-lattice
    - r-leaps
    - r-scatterplot3d
  run:
    - r-base
    - r-mass
    - r-car
    - r-cluster
    - r-ellipse
    - r-flashclust
    - r-lattice
    - r-leaps
    - r-scatterplot3d

test:
  commands:
    - $R -e "library('FactoMineR')"           # [not win]
    - "\"%R%\" -e \"library('FactoMineR')\""  # [win]

about:
  home: http://factominer.free.fr
  license: GPL (>= 2)
  summary: 'Exploratory data analysis methods to summarize, visualize and describe datasets.
    The main principal component methods are available, those with the largest potential
    in terms of applications: principal component analysis (PCA) when variables are
    quantitative, correspondence analysis (CA) and multiple correspondence analysis
    (MCA) when variables are categorical, Multiple Factor Analysis when variables are
    structured in groups, etc. and hierarchical cluster analysis. F. Husson, S. Le and
    J. Pages (2017) <DOI:10.1201/b10345-2>.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
