{% set version = "2.13" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-factominer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FactoMineR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FactoMineR/FactoMineR_{{ version }}.tar.gz
  sha256: 0967669c4b1fdbf3a34bacba353b95238f437e4ef6975f1751408d5d5eee3e6b

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-car                      # [build_platform != target_platform]
    - r-cluster                  # [build_platform != target_platform]
    - r-dt                       # [build_platform != target_platform]
    - r-ellipse                  # [build_platform != target_platform]
    - r-emmeans                  # [build_platform != target_platform]
    - r-flashclust               # [build_platform != target_platform]
    - r-ggplot2                  # [build_platform != target_platform]
    - r-ggrepel                  # [build_platform != target_platform]
    - r-lattice                  # [build_platform != target_platform]
    - r-leaps                    # [build_platform != target_platform]
    - r-mass                     # [build_platform != target_platform]
    - r-multcompview             # [build_platform != target_platform]
    - r-scatterplot3d            # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-dt
    - r-mass
    - r-car
    - r-cluster
    - r-ellipse
    - r-emmeans
    - r-flashclust
    - r-ggplot2
    - r-ggrepel
    - r-lattice
    - r-leaps
    - r-multcompview
    - r-scatterplot3d
  run:
    - r-base
    - r-dt
    - r-mass
    - r-car
    - r-cluster
    - r-ellipse
    - r-emmeans
    - r-flashclust
    - r-ggplot2
    - r-ggrepel
    - r-lattice
    - r-leaps
    - r-multcompview
    - r-scatterplot3d

test:
  commands:
    - $R -e "library('FactoMineR')"           # [not win]
    - "\"%R%\" -e \"library('FactoMineR')\""  # [win]

about:
  home: http://factominer.free.fr
  dev_url: https://github.com/husson/FactoMineR
  license: GPL-2.0-or-later
  summary: 'Exploratory data analysis methods to summarize, visualize and describe datasets. The main principal component methods are available, those with the largest potential in terms of applications: principal component analysis (PCA) when variables are quantitative, correspondence analysis (CA) and multiple correspondence
    analysis (MCA) when variables are categorical, Multiple Factor Analysis when variables are structured in groups, etc. and hierarchical cluster analysis. F. Husson, S. Le and J. Pages (2017).'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
