{% set version = '1.42' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-factominer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/FactoMineR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/FactoMineR/FactoMineR_{{ version }}.tar.gz
  sha256: 4cd9efb3681767c3bd48ddc3504ebead1493fcbbc0a9f759a00955b16c3481fa

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-car
    - r-cluster
    - r-ellipse
    - r-flashclust
    - r-lattice
    - r-leaps
    - r-scatterplot3d
  run:
    - r-base
    - r-mass
    - r-car
    - r-cluster
    - r-ellipse
    - r-flashclust
    - r-lattice
    - r-leaps
    - r-scatterplot3d

test:
  commands:
    - $R -e "library('FactoMineR')"           # [not win]
    - "\"%R%\" -e \"library('FactoMineR')\""  # [win]

about:
  home: http://factominer.free.fr
  license: GPL (>= 2)
  summary: 'Exploratory data analysis methods to summarize, visualize and describe datasets.
    The main principal component methods are available, those with the largest potential
    in terms of applications: principal component analysis (PCA) when variables are
    quantitative, correspondence analysis (CA) and multiple correspondence analysis
    (MCA) when variables are categorical, Multiple Factor Analysis when variables are
    structured in groups, etc. and hierarchical cluster analysis. F. Husson, S. Le and
    J. Pages (2017).'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: FactoMineR
# Version: 1.42
# Date: 2019-07-03
# Title: Multivariate Exploratory Data Analysis and Data Mining
# Author: Francois Husson, Julie Josse, Sebastien Le, Jeremy Mazet
# Maintainer: Francois Husson <francois.husson@agrocampus-ouest.fr>
# Depends: R (>= 3.0.0)
# Imports: car,cluster,ellipse,flashClust,graphics,grDevices,lattice,leaps,MASS,scatterplot3d,stats,utils
# Suggests: missMDA,knitr
# Description: Exploratory data analysis methods to summarize, visualize and describe datasets. The main principal component methods are available, those with the largest potential in terms of applications: principal component analysis (PCA) when variables are quantitative, correspondence analysis (CA) and multiple correspondence analysis (MCA) when variables are categorical, Multiple Factor Analysis when variables are structured in groups, etc. and hierarchical cluster analysis. F. Husson, S. Le and J. Pages (2017).
# License: GPL (>= 2)
# URL: http://factominer.free.fr
# Encoding: latin1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-07-03 09:52:25 UTC; husson
# Repository: CRAN
# Date/Publication: 2019-07-03 10:20:03 UTC
