appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: JC6VGs4ttXO3T/Hr3z9XjGVYzC4eiU2wcU7LZWcsfARNUmU8fUrHfF7UcvgrJOjHoNzxPQcM7OCV05SIb8aGFuNouC06gZCpvpqLS3Be0+hRuG5iP6NisxtI6Ec3tzzqn7jxarBNPyte58wg5PGWu4B8HqZnBH73lDtzbY5hlBefg2dT8U1Pa8tDOVVGQ4Wyna2H/FdtFzwAkSfoz5shtx9iWm6gtCOlSk9q+FPMwo9ysexiAw+ji99r4CrFP5xQR+lQBczOo2cudAAVTpYQBg80EqjDcV7dT1Qz6WW0RbKm697hpHrGrdnBNlBfWBvQ5a4tz11O60bcsKbgzyRTI1J1XUBHjHsWbHGiu+0kf+zBIDs8sIqmkB9zlunn7Wzw9lPwIgsDdGfsvHxVEDTD+TdpsfavpYCSxVmHWE8NOHEyr3mArPQTDdPDG+QYQuEMIf/768XwZhGqIBOkfXUAFMm9cPCemO2ZqMkEtlJafVifOIaNIgdTJqIJFhz73zn1inndqFzQZz3sXTLeXhlPLHhXP5/UaVULA8HRskBMEa9f7ver0xkgKnQcxQVv8veqXeDISeRgCCBGpQEdrpTH4iiyYrcO1tktDxYAEWXF3TApeC+HVa69TfZpE6x10BqGIOlijR2CjuLaOqTsRY7Iop/ldFcFL0gRs0HXwwuWvlI=
conda_forge_output_validation: true
